sudo: false
language: python
python:
  - 3.4

env:
  matrix:
    - CI_TARGET=vim
    - CI_TARGET=neovim
before_script:
  - if [ $CI_TARGET = vim ]; then
      export DISPLAY=:99.0 &&
      sh -e /etc/init.d/xvfb start;
    elif [ $CI_TARGET = neovim ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64" &&
      pip install neovim;
    fi
  - wget https://github.com/google/vroom/releases/download/v0.12.0/vroom_0.12.0-1_all.deb
  - sudo dpkg -i ./vroom_0.12.0-1_all.deb
script:
  - '[ $CI_TARGET = neovim ] && VROOM_ARGS="--neovim" || VROOM_ARGS=""'
  - vroom $VROOM_ARGS --crawl
matrix:
  fast_finish: true
  allow_failures:
    - env: CI_TARGET=neovim

addons:
  apt:
    packages:
      - vim-gnome
